Linking to Symfony Module
Codeception/codeception.github.com pull request #477
Opened 2021-03-16 17:53 UTC by ThomasLandauer

See https://github.com/Codeception/module-symfony/pull/98#issuecomment-800446510
As long as the dropdown menu does exist, I think it's better to keep Symfony in there, in order to not give the impression that Symfony isn't supported :-)
Ultimately, the dropdown should be deleted completely (or renamed to "CMS") - see https://github.com/Codeception/module-symfony/pull/98#issue-553062458

2021-03-20 00:07 UTC, Arhell approved these changes

2021-03-21 16:09 UTC, Naktibalda commented
This isn't framework dropdown, so my initial reaction was "no page - no link", but we can delete it later.

Maybe we can come up with a way to integrate Joomla and Wordpress to modules dropdown.

2021-03-21 16:10 UTC, Naktibalda requested changes

2021-03-21 16:10 UTC, Naktibalda commented on _includes/for.html
> +    <a href="https://codeception.com/docs/modules/Symfony" class="item img-thumbnail bg-white item--symfony">
Please shorten the link to `/docs/modules/Symfony`

2021-03-21 16:57 UTC, ThomasLandauer commented
> Maybe we can come up with a way to integrate Joomla and Wordpress to modules dropdown.

See https://github.com/Codeception/module-symfony/pull/98#issuecomment-800501362

2021-03-25 09:28 UTC, merged