Changed CSS: Remove text-transform: uppercase;
Codeception/codeception.github.com pull request #593
Opened 2022-01-10 15:15 UTC by NaincyKumariKnoldus

Hello! I have removed text-transform:uppercase and also I have removed the blue _ in h1:after and h2:after. Please Review my PR.
Thanks!

2022-01-10 15:21 UTC, TavoNiievez requested changes

2022-01-10 15:21 UTC, TavoNiievez commented on .vscode/launch.json
> +    ]
this file should not be included in git.

2022-01-10 19:09 UTC, Arhell reviewed
My suggestion is to roll back all the changes. Which corrected affects the entire site.

It only needs to be corrected on the documentation pages.
Add this way:

```
.page #page {
    ....
}
```

Remove the blue line only in h2, h3, etc.
In h1 it is not necessary, this is a feature of the site.

2022-02-01 22:38 UTC, Arhell commented
fix https://github.com/Codeception/codeception.github.com/pull/598

2022-02-01 22:38 UTC, closed without merging